use crate::vm::storage::StorageKind;
use std::sync::Arc;

/// Raw opcode byte before decoding into instruction with fields.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Opcode {
    ArrayConstOld,
    ArrayConst,
    ArrayPush,
    Assign,
    AssignPop,
    AssignOld,
    AttributeDefine,
    AttributeEval,
    AttributePush,
    BinaryAssignOperator,
    BinaryOperator,
    BoolConst,
    Call,
    CallOld,
    ClassDefine,
    DelegateDefine,
    DoubleConst,
    ElementEval,
    ElementPush,
    Eval,
    FloatConst,
    FunctionConst,
    FunctionDefine,
    Import,
    IntConst,
    Jump,
    JumpIfFalse,
    JumpIfNil,
    JumpIfTrue,
    Leave,
    ListAssign,
    ListAssignOld,
    LocalDefine,
    LogicalAnd,
    LogicalAndOld,
    LogicalOptional,
    LogicalOr,
    LogicalOrOld,
    LongConst,
    MapConst,
    MapConstOld,
    MapInsert,
    MethodConst,
    MethodDefine,
    ModuleConstructor,
    ModuleDefine,
    NilConst,
    Nop,
    ObjectSelector,
    Pop,
    PopOld,
    Print,
    Require,
    SetState,
    SetStateOld,
    SourceFile,
    StaticDefine,
    StringConst,
    StringPush,
    SymbolConst,
    Throw,
    TryCatch,
    UIntConst,
    ULongConst,
    UnaryAssignOperator,
    UnaryOperator,
    Undef,
    VaCall,
    VariablePush,
    VariableEval,
    VoidConst,
    Switch,
    Case,
    JumpTable,
    TailCall,
    AsyncFunction,
    Await,
    Yield,
    SuperCall,
    FastAttribute,
    RestParameter,
    OptionalParameter,
    EvalAttribute,
    EvalAttr,
    Super,
    NewTarget,
    Spread,
    ArrowFunction,
    Generator,
    YieldFrom,
    await_next,
    ReturnToYield,
    JumpUndefined,
    JumpDefined,
    LogicalNullish,
    NullishCoalescing,
    OptionalChaining,
    BigIntConst,
    TemplateConst,
    ImportMeta,
    DynamicImport,
    CodeEval,
    ByteConst,
    UByteConst,
    ShortConst,
    UShortConst,
    IteratorNext,
}

impl Opcode {
    pub fn from_byte(b: u8) -> Result<Self, String> {
        match b {
            0x00 => Ok(Opcode::ArrayConstOld),
            0x01 => Ok(Opcode::AssignOld),
            0x02 => Ok(Opcode::AttributeDefine),
            0x03 => Ok(Opcode::AttributePush),
            0x04 => Ok(Opcode::BinaryAssignOperator),
            0x05 => Ok(Opcode::BinaryOperator),
            0x06 => Ok(Opcode::Call),
            0x07 => Ok(Opcode::ClassDefine),
            0x08 => Ok(Opcode::Eval),
            0x09 => Ok(Opcode::FloatConst),
            0x0A => Ok(Opcode::FunctionDefine),
            0x0B => Ok(Opcode::Import),
            0x0C => Ok(Opcode::IntConst),
            0x0D => Ok(Opcode::Jump),
            0x0E => Ok(Opcode::JumpIfTrue),
            0x0F => Ok(Opcode::JumpIfFalse),
            0x10 => Ok(Opcode::ListAssignOld),
            0x11 => Ok(Opcode::LocalDefine),
            0x12 => Ok(Opcode::LogicalAndOld),
            0x13 => Ok(Opcode::LogicalOrOld),
            0x14 => Ok(Opcode::MethodDefine),
            0x15 => Ok(Opcode::ModuleDefine),
            0x16 => Ok(Opcode::NilConst),
            0x17 => Ok(Opcode::Nop),
            0x18 => Ok(Opcode::PopOld),
            0x19 => Ok(Opcode::Print),
            0x1A => Ok(Opcode::Require),
            0x1B => Ok(Opcode::SetStateOld),
            0x1C => Ok(Opcode::StaticDefine),
            0x1D => Ok(Opcode::StringConst),
            0x1E => Ok(Opcode::StringPush),
            0x1F => Ok(Opcode::Throw),
            0x20 => Ok(Opcode::TryCatch),
            0x21 => Ok(Opcode::UnaryAssignOperator),
            0x22 => Ok(Opcode::UnaryOperator),
            0x23 => Ok(Opcode::Undef),
            0x24 => Ok(Opcode::VariablePush),
            0x25 => Ok(Opcode::AttributeEval),
            0x26 => Ok(Opcode::VariableEval),
            0x27 => Ok(Opcode::SourceFile),
            0x28 => Ok(Opcode::FunctionConst),
            0x29 => Ok(Opcode::MethodConst),
            0x2A => Ok(Opcode::MapConstOld),
            0x2B => Ok(Opcode::LongConst),
            0x2C => Ok(Opcode::Assign),
            0x2D => Ok(Opcode::ListAssign),
            0x2E => Ok(Opcode::CallOld),
            0x2F => Ok(Opcode::ObjectSelector),
            0x30 => Ok(Opcode::SymbolConst),
            0x31 => Ok(Opcode::Leave),
            0x32 => Ok(Opcode::ArrayConst),
            0x33 => Ok(Opcode::ArrayPush),
            0x34 => Ok(Opcode::MapConst),
            0x35 => Ok(Opcode::MapInsert),
            0x36 => Ok(Opcode::Pop),
            0x37 => Ok(Opcode::SetState),
            0x38 => Ok(Opcode::VoidConst),
            0x39 => Ok(Opcode::AssignPop),
            0x3A => Ok(Opcode::UIntConst),
            0x3B => Ok(Opcode::ULongConst),
            0x3C => Ok(Opcode::DoubleConst),
            0x3D => Ok(Opcode::ElementPush),
            0x3E => Ok(Opcode::ElementEval),
            0x3F => Ok(Opcode::LogicalAnd),
            0x40 => Ok(Opcode::LogicalOr),
            0x41 => Ok(Opcode::BoolConst),
            0x42 => Ok(Opcode::ModuleConstructor),
            0x43 => Ok(Opcode::VaCall),
            0x44 => Ok(Opcode::CodeEval),
            0x45 => Ok(Opcode::DelegateDefine),
            0x46 => Ok(Opcode::JumpIfNil),
            0x47 => Ok(Opcode::LogicalOptional),
            0x48 => Ok(Opcode::ByteConst),
            0x49 => Ok(Opcode::UByteConst),
            0x4A => Ok(Opcode::ShortConst),
            0x4B => Ok(Opcode::UShortConst),
            0x50 => Ok(Opcode::IteratorNext), // IteratorNext for foreach loops
            0xF4 => Ok(Opcode::Nop),
            0x80..=0xFF => Ok(Opcode::Nop),
            _ => Err(format!("Unknown opcode byte: 0x{:02X}", b)),
        }
    }
}

/// Decoded instruction with type-safe payload.
#[derive(Debug, Clone)]
pub enum Instruction {
    ArrayConstOld { count: u32 },
    ArrayConst { count: u32 },
    ArrayPush,
    Assign { symbols: Vec<String>, storage_index: i32 },
    AssignPop,
    AssignOld { symbols: Vec<String>, index: i32 },
    AttributeDefine { symbols: Vec<String> },
    AttributeEval { symbols: Vec<String> },
    AttributePush { symbols: Vec<String>, kind: StorageKind, index: i32 },
    BinaryAssignOperator { op: String, symbols: Vec<String> },
    BinaryOperator { op: String },
    BoolConst { value: bool },
    ByteConst { value: i32 },
    UByteConst { value: i32 },
    ShortConst { value: i32 },
    UShortConst { value: i32 },
    Call { arg_count: i32 },
    CallOld { arg_count: i32 },
    ClassDefine { symbols: Vec<String> },
    DelegateDefine { name: String, target: String },
    DoubleConst { value: f64 },
    ElementEval,
    ElementPush,
    Eval,
    FloatConst { value: f32 },
    FunctionConst,
    FunctionDefine { symbols: Vec<String> },
    Import { symbols: Vec<String> },
    IntConst { value: i32 },
    Jump { target: i32 },
    JumpIfFalse { target: i32 },
    JumpIfNil { target: i32 },
    JumpIfTrue { target: i32 },
    Leave { depth: i32, rewind_locals: i32 },
    ListAssign,
    ListAssignOld,
    LocalDefine,
    LogicalAnd { target: i32 },
    LogicalAndOld { target: i32 },
    LogicalOptional,
    LogicalOr { target: i32 },
    LogicalOrOld { target: i32 },
    LongConst { value: i64 },
    MapConst,
    MapConstOld,
    MapInsert,
    MethodConst,
    MethodDefine { symbols: Vec<String> },
    ModuleConstructor,
    ModuleDefine { symbols: Vec<String> },
    NilConst,
    Nop,
    ObjectSelector { symbol: String },
    Pop,
    PopOld,
    Print { arg_count: i32 },
    Require { symbols: Vec<String> },
    SetState { state: u8 },
    SetStateOld,
    SourceFile { symbols: Vec<String> },
    StaticDefine { symbols: Vec<String> },
    StringConst { symbols: Vec<String> },
    StringPush { count: i32 },
    SymbolConst { symbol: String },
    Throw,
    TryCatch { target: i32 },
    UIntConst { value: u32 },
    ULongConst { value: u64 },
    UnaryAssignOperator { op: String, symbols: Vec<String> },
    UnaryOperator { op: String },
    Undef { symbols: Vec<String> },
    VaCall { arg_count: i32 },
    VariablePush { symbols: Vec<String>, kind: StorageKind, index: i32 },
    VariableEval { symbols: Vec<String>, kind: StorageKind, index: i32 },
    VoidConst,
    IteratorNext { target: i32, var_index: i32 }, // foreach: target=jump if done, var_index=local var for element
    Switch { default_target: i32, case_count: i32 },
    Case { value: i32, target: i32 },
    JumpTable { default_target: i32 },
    TailCall,
    AsyncFunction,
    Await,
    Yield,
    SuperCall,
    FastAttribute,
    RestParameter,
    OptionalParameter,
    EvalAttribute { symbols: Vec<String> },
    EvalAttr,
    Super,
    NewTarget,
    Spread,
    ArrowFunction,
    Generator,
    YieldFrom,
    await_next,
    ReturnToYield,
    JumpUndefined { target: i32 },
    JumpDefined { target: i32 },
    LogicalNullish { target: i32 },
    NullishCoalescing { target: i32 },
    OptionalChaining,
    BigIntConst,
    TemplateConst,
    ImportMeta,
    DynamicImport,
}

/// A code frame represents a function/module's bytecode and metadata.
#[derive(Debug, Clone)]
pub struct CodeFrame {
    pub has_debug: bool,
    pub adhoc_version: u8,
    pub param_count: i32,
    pub param_names: Vec<String>,
    pub stack_size: i32,
    pub local_var_count: i32,
    pub static_var_count: i32,
    pub instructions: Vec<Instruction>,
    pub child_frames: Vec<Arc<CodeFrame>>,
    pub instruction_lines: Vec<i32>,
}

impl Instruction {
    pub fn from_opcode_and_data(_opcode: Opcode, _cursor: &mut crate::vm::loader::Cursor) -> Result<Self, String> {
        Ok(Instruction::Nop)
    }
}